services:
  db:
    image: postgres:16-alpine
    container_name: food_delivery_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_delivery_db
    ports:
      - "5432:5432"
    volumes:
      - food_delivery_data:/var/lib/postgresql/data

volumes:
  food_delivery_data:
